### ISSUE TITLE
Bug: hyphen between number

### ISSUE THREAD

**Issue by lilywang711** [Jinjiang/zhlint#11]
e.g.

`xx.md` 内容为：`1-1`

执行 `zhlint xx.md` 出现以下错误
```
[start] xxxx.md
TypeError: Cannot read property 'content' of undefined
    at module.exports (/Users/lily/.nvm/versions/node/v13.3.0/lib/node_modules/zhlint/src/rules/case-math-exp.js:56:60)
    at travel (/Users/lily/.nvm/versions/node/v13.3.0/lib/node_modules/zhlint/src/travel.js:21:7)
    at processRule (/Users/lily/.nvm/versions/node/v13.3.0/lib/node_modules/zhlint/src/process-rule.js:17:3)
    at /Users/lily/.nvm/versions/node/v13.3.0/lib/node_modules/zhlint/src/run.js:127:52
    at Array.forEach (<anonymous>)
    at /Users/lily/.nvm/versions/node/v13.3.0/lib/node_modules/zhlint/src/run.js:127:36
    at Array.map (<anonymous>)
    at run (/Users/lily/.nvm/versions/node/v13.3.0/lib/node_modules/zhlint/src/run.js:124:54)
    at /Users/lily/.nvm/versions/node/v13.3.0/lib/node_modules/zhlint/bin/index.js:35:39
    at Array.map (<anonymous>)


```

**Comment by AngusFu** [comment]
+1
